In [14]:
!pip install pybaseball > null

In [18]:
from pybaseball import get_splits
from pybaseball import playerid_lookup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')
pd.set_option('display.max_columns', 500)
color_pal = plt.rcParams["axes.prop_cycle"].by_key()["color"]

In [99]:
# find Scott Hatteberg's player id (mlbam_key)
key_bbref = playerid_lookup('hatteberg', 'scott').loc[0, 'key_bbref']
active_years = []

# get all available date
career_total = get_splits(key_bbref)

# each year separated into it's table

C:\Users\marti\anaconda3\Lib\site-packages\pybaseball\split_stats.py:71: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  commentsoup = bs.BeautifulSoup(comment[i], 'lxml')

In [100]:
career_total

                                    G    GS    PA    AB     R     H   2B  3B  \
Split Type     Split
Season Totals  Career Totals     1314  1106  4876  4226   538  1153  249   7
Platoon Splits vs RHP            1230  <NA>  3858  3344   443   945  206   6
               vs LHP             587  <NA>  1018   882    95   208   43   1
               vs RHP as LHB     1230  <NA>  3858  3344  <NA>   945  206   6
               vs LHP as LHB      587  <NA>  1018   882  <NA>   208   43   1
...                               ...   ...   ...   ...   ...   ...  ...  ..
Ballparks      TBD-TropicanaFld    39    36   159   138    24    38    5   1
               ATL-Turner Fld      12    10    46    38     8     7    1   0
               PHI-VeteransStad     5     4    18    15     3     3    3   0
               CHC-Wrigley Fld     16    12    54    41     3     5    1   0
               NYY-Yankee Stad     29    25   111    97    17    30    8   0

                                  HR  RBI  SB  CS   BB   SO     BA    OBP  \
Split Type     Split
Season Totals  Career Totals     106  527   3   8  562  503  0.273  0.361
Platoon Splits vs RHP             90  413   2   6  462  363  0.283  0.371
               vs LHP             16  114   1   2  100  140  0.236  0.327
               vs RHP as LHB      90  413   0   0  462  363  0.283  0.371
               vs LHP as LHB      16  114   0   0  100  140  0.236  0.327
...                              ...  ...  ..  ..  ...  ...    ...    ...
Ballparks      TBD-TropicanaFld    7   19   0   0   16   21  0.275  0.371
               ATL-Turner Fld      1    4   0   0    6    7  0.184  0.283
               PHI-VeteransStad    0    2   0   0    3    4    0.2  0.333
               CHC-Wrigley Fld     0    5   0   0   12    5  0.122  0.315
               NYY-Yankee Stad     3   13   0   0   13    8  0.309  0.396

                                   SLG    OPS    TB  GDP  HBP  SH  SF  IBB  \
Split Type     Split
Season Totals  Career Totals      0.41  0.772  1734  117   42  15  31   27
Platoon Splits vs RHP            0.429  0.799  1433   99   20   7  25   27
               vs LHP            0.341  0.668   301   18   22   8   6    0
               vs RHP as LHB     0.429  0.799  1433   99   20   7  25   27
               vs LHP as LHB     0.341  0.668   301   18   22   8   6    0
...                                ...    ...   ...  ...  ...  ..  ..  ...
Ballparks      TBD-TropicanaFld  0.478  0.849    66    4    5   0   0    0
               ATL-Turner Fld     0.29  0.572    11    2    0   0   2    2
               PHI-VeteransStad    0.4  0.733     6    0    0   0   0    0
               CHC-Wrigley Fld   0.146  0.461     6    0    0   0   1    0
               NYY-Yankee Stad   0.485  0.881    47    3    1   0   0    0

                                 ROE  BAbip  tOPS+   1B
Split Type     Split
Season Totals  Career Totals      44  0.287    100  791
Platoon Splits vs RHP             38  0.293    107  643
               vs LHP              6  0.262     74  148
               vs RHP as LHB      38  0.293    107  643
               vs LHP as LHB       6  0.262     74  148
...                              ...    ...    ...  ...
Ballparks      TBD-TropicanaFld    1  0.282    119   25
               ATL-Turner Fld      0  0.188     49    5
               PHI-VeteransStad    0  0.273     90    0
               CHC-Wrigley Fld     0  0.135     23    4
               NYY-Yankee Stad     3  0.314    128   19

[231 rows x 28 columns]